New branch
jonathanmajh/iko_reliability pull request #7
Opened 2023-05-11 17:54 UTC by Desumai

2023-05-11 18:07 UTC, jonathanmajh requested changes

2023-05-11 18:19 UTC, jonathanmajh commented
The default for the Edit PM Name field should be the auto generated one

2023-05-11 18:48 UTC, Desumai commented on lib/admin/end_drawer.dart
> +                                .maximoServerSelected); //TODO: pause user input during load?
But it would be a problem if the user thinks the loading has finished and uploads an excel template

2023-05-11 18:50 UTC, Desumai commented on lib/admin/end_drawer.dart
> +  @override
VSCode added it by itself... I'll remove it

2023-05-11 19:34 UTC, jonathanmajh commented on lib/admin/end_drawer.dart
> +                                .maximoServerSelected); //TODO: pause user input during load?
it'll be good to lock some parts of interface during loading, but that should be a separate task / PR

2023-05-15 18:54 UTC, jonathanmajh approved these changes

2023-05-15 18:54 UTC, jonathanmajh commented on lib/admin/pm_check.dart
> +                  //why do we need a divider here? (Dustin)
having some space looks nicer since the textbox would be right at the edge otherwise.

it's a divider cause i can just copy the other one i had

2023-05-15 18:56 UTC, merged